### ISSUE TITLE
numpy version requirement

### ISSUE THREAD

**Issue by ramav87** [AFM-analysis/igor2#8]
Is it critical that the numpy version be >1.24? I did note that the test failed when I tried it, but the functionality of the package seems unaffected. Looking at the specific test that failed, it seems a minor issue regarding formatting (as far as I can see).

**Comment by paulmueller** [comment]
I think I set the numpy version due to some CVE? Is it critical for you still?

**Comment by ramav87** [comment]
This is no longer critical for us. The ecosystem worked itself out :)
